services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cajita
      POSTGRES_USER: cajita
      POSTGRES_PASSWORD: cajita
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d cajita -U cajita
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
