/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools/index'
import { Route as ApiElectricTableRouteImport } from './routes/api/electric/$table'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthDevLoginRouteImport } from './routes/api/auth/dev-login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedToolsCreatePlaylistRouteImport } from './routes/_authenticated/tools/create-playlist'
import { Route as AuthenticatedFinancesSettingsRouteImport } from './routes/_authenticated/finances/settings'
import { Route as AuthenticatedFinancesNetWorthRouteImport } from './routes/_authenticated/finances/net-worth'
import { Route as AuthenticatedFinancesExpenseCategoriesIndexRouteImport } from './routes/_authenticated/finances/expense-categories/index'
import { Route as AuthenticatedFinancesExpenseCategoriesCategoryIdRouteImport } from './routes/_authenticated/finances/expense-categories/$categoryId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiElectricTableRoute = ApiElectricTableRouteImport.update({
  id: '/api/electric/$table',
  path: '/api/electric/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevLoginRoute = ApiAuthDevLoginRouteImport.update({
  id: '/api/auth/dev-login',
  path: '/api/auth/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsCreatePlaylistRoute =
  AuthenticatedToolsCreatePlaylistRouteImport.update({
    id: '/tools/create-playlist',
    path: '/tools/create-playlist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesSettingsRoute =
  AuthenticatedFinancesSettingsRouteImport.update({
    id: '/finances/settings',
    path: '/finances/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesNetWorthRoute =
  AuthenticatedFinancesNetWorthRouteImport.update({
    id: '/finances/net-worth',
    path: '/finances/net-worth',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesExpenseCategoriesIndexRoute =
  AuthenticatedFinancesExpenseCategoriesIndexRouteImport.update({
    id: '/finances/expense-categories/',
    path: '/finances/expense-categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesExpenseCategoriesCategoryIdRoute =
  AuthenticatedFinancesExpenseCategoriesCategoryIdRouteImport.update({
    id: '/finances/expense-categories/$categoryId',
    path: '/finances/expense-categories/$categoryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances/net-worth': typeof AuthenticatedFinancesNetWorthRoute
  '/finances/settings': typeof AuthenticatedFinancesSettingsRoute
  '/tools/create-playlist': typeof AuthenticatedToolsCreatePlaylistRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/electric/$table': typeof ApiElectricTableRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/finances/expense-categories/$categoryId': typeof AuthenticatedFinancesExpenseCategoriesCategoryIdRoute
  '/finances/expense-categories/': typeof AuthenticatedFinancesExpenseCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finances/net-worth': typeof AuthenticatedFinancesNetWorthRoute
  '/finances/settings': typeof AuthenticatedFinancesSettingsRoute
  '/tools/create-playlist': typeof AuthenticatedToolsCreatePlaylistRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/electric/$table': typeof ApiElectricTableRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/finances/expense-categories/$categoryId': typeof AuthenticatedFinancesExpenseCategoriesCategoryIdRoute
  '/finances/expense-categories': typeof AuthenticatedFinancesExpenseCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finances/net-worth': typeof AuthenticatedFinancesNetWorthRoute
  '/_authenticated/finances/settings': typeof AuthenticatedFinancesSettingsRoute
  '/_authenticated/tools/create-playlist': typeof AuthenticatedToolsCreatePlaylistRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/dev-login': typeof ApiAuthDevLoginRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/electric/$table': typeof ApiElectricTableRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/finances/expense-categories/$categoryId': typeof AuthenticatedFinancesExpenseCategoriesCategoryIdRoute
  '/_authenticated/finances/expense-categories/': typeof AuthenticatedFinancesExpenseCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/finances/net-worth'
    | '/finances/settings'
    | '/tools/create-playlist'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/electric/$table'
    | '/tools/'
    | '/finances/expense-categories/$categoryId'
    | '/finances/expense-categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/finances/net-worth'
    | '/finances/settings'
    | '/tools/create-playlist'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/electric/$table'
    | '/tools'
    | '/finances/expense-categories/$categoryId'
    | '/finances/expense-categories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/finances/net-worth'
    | '/_authenticated/finances/settings'
    | '/_authenticated/tools/create-playlist'
    | '/api/auth/callback'
    | '/api/auth/dev-login'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/electric/$table'
    | '/_authenticated/tools/'
    | '/_authenticated/finances/expense-categories/$categoryId'
    | '/_authenticated/finances/expense-categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDevLoginRoute: typeof ApiAuthDevLoginRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiElectricTableRoute: typeof ApiElectricTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/electric/$table': {
      id: '/api/electric/$table'
      path: '/api/electric/$table'
      fullPath: '/api/electric/$table'
      preLoaderRoute: typeof ApiElectricTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev-login': {
      id: '/api/auth/dev-login'
      path: '/api/auth/dev-login'
      fullPath: '/api/auth/dev-login'
      preLoaderRoute: typeof ApiAuthDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/create-playlist': {
      id: '/_authenticated/tools/create-playlist'
      path: '/tools/create-playlist'
      fullPath: '/tools/create-playlist'
      preLoaderRoute: typeof AuthenticatedToolsCreatePlaylistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/settings': {
      id: '/_authenticated/finances/settings'
      path: '/finances/settings'
      fullPath: '/finances/settings'
      preLoaderRoute: typeof AuthenticatedFinancesSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/net-worth': {
      id: '/_authenticated/finances/net-worth'
      path: '/finances/net-worth'
      fullPath: '/finances/net-worth'
      preLoaderRoute: typeof AuthenticatedFinancesNetWorthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/expense-categories/': {
      id: '/_authenticated/finances/expense-categories/'
      path: '/finances/expense-categories'
      fullPath: '/finances/expense-categories/'
      preLoaderRoute: typeof AuthenticatedFinancesExpenseCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/expense-categories/$categoryId': {
      id: '/_authenticated/finances/expense-categories/$categoryId'
      path: '/finances/expense-categories/$categoryId'
      fullPath: '/finances/expense-categories/$categoryId'
      preLoaderRoute: typeof AuthenticatedFinancesExpenseCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancesNetWorthRoute: typeof AuthenticatedFinancesNetWorthRoute
  AuthenticatedFinancesSettingsRoute: typeof AuthenticatedFinancesSettingsRoute
  AuthenticatedToolsCreatePlaylistRoute: typeof AuthenticatedToolsCreatePlaylistRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedFinancesExpenseCategoriesCategoryIdRoute: typeof AuthenticatedFinancesExpenseCategoriesCategoryIdRoute
  AuthenticatedFinancesExpenseCategoriesIndexRoute: typeof AuthenticatedFinancesExpenseCategoriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancesNetWorthRoute: AuthenticatedFinancesNetWorthRoute,
  AuthenticatedFinancesSettingsRoute: AuthenticatedFinancesSettingsRoute,
  AuthenticatedToolsCreatePlaylistRoute: AuthenticatedToolsCreatePlaylistRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedFinancesExpenseCategoriesCategoryIdRoute:
    AuthenticatedFinancesExpenseCategoriesCategoryIdRoute,
  AuthenticatedFinancesExpenseCategoriesIndexRoute:
    AuthenticatedFinancesExpenseCategoriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDevLoginRoute: ApiAuthDevLoginRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiElectricTableRoute: ApiElectricTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
